### ISSUE TITLE
there is no dat file about density. How did it compute density?

### ISSUE THREAD

**Issue by wangxiaochen19960107** [jonnydyer/pypropep#12]

**Comment by jamesdkelly15** [comment]
Propellant dat file is located here that contains density data:

[pypropep/data/propellant.dat](https://github.com/jonnydyer/pypropep/blob/6894df3e7cdbb82475b2c98f7184ca12cd1600e9/pypropep/data/propellant.dat)

**Comment by wangxiaochen19960107** [comment]
> Propellant dat file is located here that contains density data:
> 
> [pypropep/data/propellant.dat](https://github.com/jonnydyer/pypropep/blob/6894df3e7cdbb82475b2c98f7184ca12cd1600e9/pypropep/data/propellant.dat)

Thanks for your reply. The propellant.dat file don't contain propellant density(it has id, element composition and enhalthy), but when I add propellant, the object has the density attribute, it makes me confused.

**Comment by wangxiaochen19960107** [comment]
> > Propellant dat file is located here that contains density data:
> > [pypropep/data/propellant.dat](https://github.com/jonnydyer/pypropep/blob/6894df3e7cdbb82475b2c98f7184ca12cd1600e9/pypropep/data/propellant.dat)
> 
> Thanks for your reply. The propellant.dat file don't contain propellant density(it has id, element composition and enhalthy), but when I add propellant, the object has the density attribute, it makes me confused.

I get it,thank you!
